name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # - name: Navigate to aws_infra-tf directory
      #   run: cd aws_infra-tf
      - name: Terraform Init
        run: cd aws_infra-tf && terraform init

      - name: Terraform Plan
        run: |
          (cd aws_infra-tf && terraform plan -var-file="variables/dev.tfvars" -out=tfplan)

      - name: Terraform Apply
        timeout-minutes: 5
        run: |
          (cd aws_infra-tf && terraform apply -var-file="variables/dev.tfvars" -auto-approve)

      - name: Terraform Destroy
        if: always()
        run:  (cd aws_infra-tf && terraform destroy -var-file="variables/dev.tfvars" -auto-approve)